package com.hibernateassist.database;

import java.sql.SQLException;
import java.text.ParseException;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Logger;

import org.hibernate.SQLQuery;
import org.json.JSONArray;
import org.json.JSONObject;

import com.hibernateassist.common.CommonUtil;
import com.hibernateassist.common.CommonUtil.jsPlumbArrowPosition;

/**
 * @author vicky.thakor
 */
public class MySQLAnalyser extends AbstractDAO implements Analyser{
	
	enum MySQLOperation{
		ordering_operation, grouping_operation, nested_loop, table;
	}
	
	enum MySQLTableProperties{
		table_name, access_type, possible_keys, key, used_key_parts, 
		key_length, ref, rows, filtered, index_condition, 
		attached_condition, using_join_buffer, message; 
	}
	
	private static final Logger logger = Logger.getLogger(MySQLAnalyser.class.getName());
	
	/**
	 * Generate Query report from Hibernate Criteria.
	 * @author vicky.thakor
	 * @param hibernateQuery
	 * @param actualQuery
	 * @param reportFolderPath
	 * @throws ClassNotFoundException
	 * @throws SQLException
	 */
	@Override
	public void generateQueryReport(String hibernateQuery, String actualQuery, String reportFolderPath, String strFilenamePrefix) throws ClassNotFoundException, SQLException {
		String strExecutionPlan = getExecutionPlan(actualQuery);
		if(strExecutionPlan != null && !strExecutionPlan.isEmpty()){
				try {
					JSONObject QueryPlan = new JSONObject(strExecutionPlan);
					
					StringBuilder HTMLReport = new StringBuilder("");
					HTMLReport.append(CommonUtil.getHTMLReportHeader());
					HTMLReport.append("<div class=\"graphical_data\">");
					HTMLReport.append("<div class=\"operation_header\">");
					HTMLReport.append("<h3>Execution Plan - MySQL</h3>");
					HTMLReport.append("It is the graphical representation of query executed on database. Each node in it plays significant role in query. Click on node for more information.");
					HTMLReport.append("</div>");
					HTMLReport.append("<div style=\"position:relative\">");
					HTMLReport.append("<div id=\"nodeDetails\"></div>");
					HTMLReport.append("<div style=\"font-size:13px;height:500px;max-height:500px;overflow:scroll;position:relative\" class=\"whiteFadedbox\">");
					int parentNode = parseJSON(QueryPlan.getJSONObject("query_block"), 0,HTMLReport);
					parentNode = parentNode + 1;
					HTMLReport.append("<script>");
					HTMLReport.append("$(\"#tableBlock").append(parentNode - 1).append("\").prepend(\"<div id=\\\"tableBlock").append(parentNode).append("\\\"><div class=\\\"queryBlockMySQL\\\" id=\\\"parent").append((parentNode)).append("\\\">query_block</div></div>\");");
					if(parentNode == 1){
						/* In case of single table return */
						HTMLReport.append(CommonUtil.getjsPlumbScript("parent0", "parent1", jsPlumbArrowPosition.TopCenter, jsPlumbArrowPosition.BottomCenter));
					}
					HTMLReport.append("</script>");
					HTMLReport.append("</div>");
					HTMLReport.append("</div>");
					HTMLReport.append("</div>");
					HTMLReport.append("<div class=\"statistics_data\">");
					HTMLReport.append("<div class=\"operation_header\"><h3>Query Statistics</h3>");
					HTMLReport.append("Data shows actual query generated by Hibernate.");
					HTMLReport.append("</div>");
					HTMLReport.append("<div class=\"whiteFadedbox\" style=\"overflow:scroll;height:100px;font-size:15px\">");
					HTMLReport.append(hibernateQuery);
					HTMLReport.append("</div>");
					HTMLReport.append("</div>");
					HTMLReport.append(CommonUtil.getHTMLReportFooter());
					
					reportFolderPath = reportFolderPath == null ? "" : reportFolderPath;
					new CommonUtil().createHTMLReportFile(HTMLReport.toString(), strFilenamePrefix, reportFolderPath);
				} catch (ParseException e) {
					e.printStackTrace();
				}
		}else{
			logger.info("Execution plan not found on database.");
		}
	}
	
	/**
	 * Get Execution Plan JSON from MySQL.
	 * @author vicky.thakor
	 * @param query
	 * @return
	 * @throws ClassNotFoundException
	 * @throws SQLException
	 */
	private String getExecutionPlan(String query) throws ClassNotFoundException, SQLException{
		String strExecutionPlan =  null;
		if(query == null || query.isEmpty()){
			logger.info("Please provide valid query");
		}else if(getHibernateSession() != null){
			String strDatabaseVersion = getDatabaseVersion();
        	strDatabaseVersion = strDatabaseVersion.substring(0, strDatabaseVersion.indexOf(".") + 2);
        	double doubleVersion = Double.valueOf(strDatabaseVersion);
        	/**
        	 * MySQL 5.6 and above supports EXPLAIN with JSON format.
        	 */
        	if(doubleVersion >= 5.6){
        		SQLQuery objSQLQuery = getHibernateSession().createSQLQuery("EXPLAIN format = JSON "+query);
        		List<String> executionPlanDetails = objSQLQuery.list();
        		strExecutionPlan = executionPlanDetails.get(0);
        	}
		}
		return strExecutionPlan;
	}
	
	/**
	 * Recursive method call to parse all MySQL operation.
	 * @author vicky.thakor
	 * @param obj
	 * @param parentNode
	 * @param stringBuilderHTMLReport
	 * @return
	 */
	private int parseJSON(JSONObject obj, int parentNode, StringBuilder stringBuilderHTMLReport){
		if(obj != null){
			if(obj.has(MySQLOperation.table.toString())){
				parseTableNode(obj.getJSONObject("table"), parentNode, stringBuilderHTMLReport);
			}else if(obj.has(MySQLOperation.nested_loop.toString())){
				JSONArray jsonArrayTable = obj.getJSONArray(MySQLOperation.nested_loop.toString());
				for(int i = 0; i < jsonArrayTable.length(); i++){
					parentNode = i;
					parentNode = parseJSON(jsonArrayTable.getJSONObject(i), parentNode, stringBuilderHTMLReport);
					
					stringBuilderHTMLReport.append("<script>");
					if((i+1) == jsonArrayTable.length()){
						stringBuilderHTMLReport.append(CommonUtil.getjsPlumbScript("parent"+parentNode, "parent"+(parentNode+1), jsPlumbArrowPosition.TopCenter, jsPlumbArrowPosition.BottomCenter));
					}else{
						stringBuilderHTMLReport.append(CommonUtil.getjsPlumbScript("parent"+parentNode, "parent"+(parentNode+1), jsPlumbArrowPosition.RightMiddle, jsPlumbArrowPosition.LeftMiddle));
					}
					stringBuilderHTMLReport.append("</script>");
				}
			}else if(obj.has(MySQLOperation.grouping_operation.toString())){
				JSONObject jsonObjectGroupingOperation = obj.getJSONObject(MySQLOperation.grouping_operation.toString());
				parentNode = parseJSON(jsonObjectGroupingOperation, parentNode, stringBuilderHTMLReport);
				
				
				StringBuilder nodeAttribute = new StringBuilder("");
				Iterator<String> iteratorProperties = jsonObjectGroupingOperation.keys();
				while(iteratorProperties.hasNext()){
					/* Get key from JSONObject */
					String property = iteratorProperties.next();
					if(!(jsonObjectGroupingOperation.get(property) instanceof JSONObject)
							&& !(jsonObjectGroupingOperation.get(property) instanceof JSONArray)){
						/* Get value of key */
						String propertyValue = jsonObjectGroupingOperation.getString(property);
						nodeAttribute.append(property).append(" = ").append(" \\\"<b>").append(property).append("</b>: ").append(propertyValue.replace("\"","")).append("\\\"").append(" ");
					}
				}
				
				stringBuilderHTMLReport.append("<script>");
				if(parentNode == 0){
					/* In case of single table return */
					stringBuilderHTMLReport.append(CommonUtil.getjsPlumbScript("parent0", "parent1", jsPlumbArrowPosition.TopCenter, jsPlumbArrowPosition.BottomCenter));
				}
				parentNode = parentNode + 1;
				
				stringBuilderHTMLReport.append("$(\"#tableBlock").append(parentNode-1).append("\").prepend(\"<div id=\\\"tableBlock").append(parentNode).append("\\\"><div class=\\\"groupByMySQL nodeImage\\\" id=\\\"parent").append((parentNode)).append("\\\" ").append(nodeAttribute).append(">GROUP</div></div>\");");
				stringBuilderHTMLReport.append(CommonUtil.getjsPlumbScript("parent"+parentNode, "parent"+(parentNode+1), jsPlumbArrowPosition.TopCenter, jsPlumbArrowPosition.BottomCenter));
				stringBuilderHTMLReport.append("</script>");
			}else if(obj.has(MySQLOperation.ordering_operation.toString())){
				JSONObject jsonObjectOrderingOperation = obj.getJSONObject(MySQLOperation.ordering_operation.toString());
				parentNode = parseJSON(jsonObjectOrderingOperation, parentNode, stringBuilderHTMLReport);
				
				StringBuilder nodeAttribute = new StringBuilder("");
				Iterator<String> iteratorProperties = jsonObjectOrderingOperation.keys();
				while(iteratorProperties.hasNext()){
					/* Get key from JSONObject */
					String property = iteratorProperties.next();
					
					if(!(jsonObjectOrderingOperation.get(property) instanceof JSONObject)
							&& !(jsonObjectOrderingOperation.get(property) instanceof JSONArray)){
						/* Get value of key */
						String propertyValue = jsonObjectOrderingOperation.getString(property);
						nodeAttribute.append(property).append(" = ").append(" \\\"<b>").append(property).append("</b>: ").append(propertyValue.replace("\"","")).append("\\\"").append(" ");
					}
				}
				
				stringBuilderHTMLReport.append("<script>");
				if(parentNode == 0){
					/* In case of single table return */
					stringBuilderHTMLReport.append(CommonUtil.getjsPlumbScript("parent0", "parent1", jsPlumbArrowPosition.TopCenter, jsPlumbArrowPosition.BottomCenter));
				}
				parentNode = parentNode + 1;
				stringBuilderHTMLReport.append("$(\"#tableBlock").append(parentNode-1).append("\").prepend(\"<div id=\\\"tableBlock").append(parentNode).append("\\\"><div class=\\\"orderByMySQL nodeImage\\\" id=\\\"parent").append((parentNode)).append("\\\" ").append(nodeAttribute).append(">ORDER</div></div>\");");
				stringBuilderHTMLReport.append(CommonUtil.getjsPlumbScript("parent"+parentNode, "parent"+(parentNode+1), jsPlumbArrowPosition.TopCenter, jsPlumbArrowPosition.BottomCenter));
				stringBuilderHTMLReport.append("</script>");
			}
		}
		return parentNode;
	}
	
	/**
	 * Get table node.
	 * @author vicky.thakor
	 * @param objTableNode
	 * @param parentNode
	 * @param stringBuilder
	 */
	private void parseTableNode(JSONObject objTableNode, int parentNode, StringBuilder stringBuilder){
		if(objTableNode != null){
			stringBuilder.append("<div class=\"tableBlockMySQL\"").append(" id=\"tableBlock").append(parentNode).append("\">");
			if(parentNode <= 0){
				stringBuilder.append("<div id=\"parent").append(parentNode).append("\" class=\"connectionDot\"></div>");
			}else{
				/*stringBuilder.append("<div class=\"nestedLoopDivMySQL\"><div id=\"parent").append(parentNode).append("\"><div style=\"height:32px\"></div>nested loop</div></div>");*/
				stringBuilder.append("<div class=\"nestedLoopDivMySQL\" id=\"parent").append(parentNode).append("\"><div style=\"height:7px\"></div>nested loop</div>");
			}
			/* Impossible WHERE noticed after reading const tables */
			boolean messageFound = false;
			int rowCount = 0;
			
			/* Attach runtime style to node */
			String nodeStyle = "";
			StringBuilder nodeAttribute = new StringBuilder("");
			String nodeContent = "";
			
			/* Loop through all properties of JSONObject("table") */
			Iterator<String> iteratorProperties = objTableNode.keys();
			while(iteratorProperties.hasNext()){
				/* Get key from JSONObject */
				String property = iteratorProperties.next();
				/* Get value of key */
				String propertyValue = objTableNode.getString(property);
				
				nodeAttribute.append(property).append(" = ").append(" \"<b>").append(property).append("</b>: ").append(propertyValue.replace("\"","")).append("\"").append(" ");
				
				if("rows".equalsIgnoreCase(property) && propertyValue != null && propertyValue.matches("[0-9]*")){
					rowCount = Integer.valueOf(propertyValue);
				}
				
				if(MySQLTableProperties.access_type.toString().equalsIgnoreCase(property)){
					if("ALL".equalsIgnoreCase(propertyValue)){
						nodeContent += "Full Table Scan";
						/* rgb(245, 110, 110): nearly `red` */
						nodeStyle = "background-color: rgb(245, 110, 110);";
					}else if("range".equalsIgnoreCase(propertyValue)){
						nodeContent += "Index Range Scan";
						/* rgb(215, 169, 26): nearly `brown` */
						nodeStyle = "background-color: rgb(215, 169, 26);";
					}else if("const".equalsIgnoreCase(propertyValue)){
						nodeContent += "Single Row(Constant)";
						/* rgb(26, 107, 215): nearly `blue` */
						nodeStyle = "background-color: rgb(26, 107, 215);";
					}else if("ref".equalsIgnoreCase(propertyValue)){
						nodeContent += "Non-Unique Key Lookup";
						nodeStyle = "background-color: green;";
					}else if("eq_ref".equalsIgnoreCase(propertyValue)){
						nodeContent += "Unique Key Lookup";
						nodeStyle = "background-color: green;";
					}
				}else if(MySQLTableProperties.message.toString().equalsIgnoreCase(property)){
					nodeContent += "Impossible Query";
					/* rgb(245, 110, 110): nearly `red` */
					nodeStyle = "background-color: rgb(245, 110, 110);";
					messageFound = true;
				}
			}
			
			String prepareTableBlock = "<div id=\"child"+parentNode+"\" class=\"tableBlockContentMySQL nodeImage\" style=\""+nodeStyle+"\" "+nodeAttribute+">";
			/* Display row count top-right corner */
			prepareTableBlock += "<div style=\"position: absolute; top: -15px; right: 0px;color:black; font-size: 11px;\">"+rowCount+" row(s)</div>";
			prepareTableBlock += nodeContent;
			prepareTableBlock += "</div>";
			
			/* Append TableBlock to stringBuilder */
			stringBuilder.append(prepareTableBlock);
			stringBuilder.append("<script>");
			stringBuilder.append(CommonUtil.getjsPlumbScript("child"+parentNode, "parent"+parentNode, jsPlumbArrowPosition.TopCenter, jsPlumbArrowPosition.BottomCenter));
			
			stringBuilder.append("</script>");
			
			if(objTableNode.has(MySQLTableProperties.table_name.toString())){
				stringBuilder.append(objTableNode.get(MySQLTableProperties.table_name.toString()));
			}
			
			if(objTableNode.has(MySQLTableProperties.key.toString())){
				stringBuilder.append("<div style=\"font-size:11px;font-weight:bold\">").append(objTableNode.get(MySQLTableProperties.key.toString())).append("</div>");
			}
			
			if(messageFound){
				stringBuilder.append("<div style=\"font-size:11px;font-weight:bold\">Impossible WHERE noticed after reading const tables</div>");
			}
			
			stringBuilder.append("</div>");
		}
	}
}
